version: '3.8'

services:
  db:
    container_name: postgres-popdesign
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Password1"
      POSTGRES_DB: PopLume
    ports:
      - 5432:5432
  popdesign-api:
    container_name: popdesign-api
    build:
      context: .
      dockerfile: "./docker/dockerfile-poplumeapi"
    depends_on:
      - db
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__PopLumeApi: Host=db;Port=5432;Database=PopLume;Username=postgres;Password=Password1
    ports:
      - "8081:8080"

#  popdesign-app:
#    container_name: popdesign-app
#    build:
#      context: .
#      dockerfile: "./docker/dockerfile-popdesignApp"
#    depends_on:
#      - popdesign-api
#    restart: always
#    ports:
#      - "8080:80"
