ARG IMAGE_TAG=10.0-noble

FROM mcr.microsoft.com/dotnet/aspnet:$IMAGE_TAG AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:$IMAGE_TAG AS build
WORKDIR /

# Copia os arquivos de projeto primeiro para restaurar as dependências e aproveitar o cache do Docker
COPY ["src/API/PopLume.Api/PopLume.Api.csproj", "src/PopLume.Api/"]
COPY ["src/API/PopLume.Application/PopLume.Application.csproj", "src/PopLume.Application/"]
COPY ["src/API/PopLume.Domain/PopLume.Domain.csproj", "src/PopLume.Domain/"]
COPY ["src/API/PopLume.Infrastructure/PopLume.Infrastructure.csproj", "src/PopLume.Infrastructure/"]

RUN dotnet restore "src/PopLume.Api/PopLume.Api.csproj"

# Copia o restante do código fonte
COPY . .
WORKDIR "/src/PopLume.Api"
RUN dotnet build "./PopLume.Api.csproj" -c Release -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
RUN dotnet publish "PopLume.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PopLume.Api.dll"]
