// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PopLume.Infrastructure.DataProvider.Context;

#nullable disable

namespace PopLume.Infrastructure.Migrations
{
    [DbContext(typeof(PopLumeDbContext))]
    [Migration("20260616012229_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PopLume.Domain.Entities.Equipamento", b =>
                {
                    b.Property<Guid>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Potencia")
                        .HasColumnType("integer");

                    b.HasKey("IdEquipamento");

                    b.ToTable("Equipamento", (string)null);
                });

            modelBuilder.Entity("PopLume.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecoCusto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("QuantidadeFilamento")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("TempoImpressao")
                        .HasColumnType("integer");

                    b.HasKey("IdProduto");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("PopLume.Domain.Entities.ProdutoComposicao", b =>
                {
                    b.Property<Guid>("IdProdutoComposicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdProdutoFilho")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdProdutoPai")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("IdProdutoComposicao");

                    b.HasIndex("IdProdutoFilho");

                    b.HasIndex("IdProdutoPai", "IdProdutoFilho")
                        .IsUnique();

                    b.ToTable("Produto_Composicao", (string)null);
                });

            modelBuilder.Entity("PopLume.Domain.Entities.ProdutoComposicao", b =>
                {
                    b.HasOne("PopLume.Domain.Entities.Produto", "ProdutoFilho")
                        .WithMany("ComposicoesFilho")
                        .HasForeignKey("IdProdutoFilho")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PopLume.Domain.Entities.Produto", "ProdutoPai")
                        .WithMany("ComposicoesPai")
                        .HasForeignKey("IdProdutoPai")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProdutoFilho");

                    b.Navigation("ProdutoPai");
                });

            modelBuilder.Entity("PopLume.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ComposicoesFilho");

                    b.Navigation("ComposicoesPai");
                });
#pragma warning restore 612, 618
        }
    }
}
